<?php
$get_parm = $this->getRequest()->getParams();
$todayDate = Mage::app()->getLocale()->date()->toString(Varien_Date::DATE_INTERNAL_FORMAT);
$offerss   = Mage::getResourceModel('dealoffer/offers_collection')
 			->addStoreFilter(Mage::app()->getStore())
			->addFilter('status', 1)
			->customaddFilter('end_date', $todayDate ,">=")
			->customaddFilter('category_id', $get_parm['id'] ,"=")
		  ;
	
		//$offerss->setOrder('name', 'asc');
		$offerss->GroupbyAdd('entity_id');
$category = Mage::getModel('catalog/category')->load($get_parm['id']);
?>
<script src="<?php echo $this->getJsUrl(); ?>d4u_dealoffer/countdown.js" type="text/javascript"></script>
<link rel='stylesheet' id='camera-css'  href="<?php echo $this->getSkinUrl('d4u_dealoffer/deal.css');?>" type='text/css' media='all'>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_offerss = $offerss; ?>
<div class="page-title offers-title">
	<h1><?php echo Mage::helper('dealoffer')->__($category->getName(). ' Deals') ?></h1>
</div>
<?php
 if (!empty($_offerss)) :?>
<div class="dela_offer">
	<?php 
	$j=0;
	foreach ($_offerss as $_offers) : 
	$data = $_offers->getData();
	$current_cat = $data['category_id'];
	?>
		<div class="itemcategory">
			<div style="height:45px;">
			<div class="time" id="countboxoffer1_<?php echo $j?>" style="float:right"></div>
				<script>
					  divlists.push('countboxoffer1_<?php echo $j."&&||&&".date("Y/m/d", strtotime($data['end_date']));?>') ;
				</script>
		
			</div>
			
			<?php if ($_offers->getDealImage()) :?>
			<div class="itemcategory_center_image">
			 <a href="<?php echo $_offers->getOffersUrl();?>" title="<?php echo $this->htmlEscape($_offers->getName()) ?>" class='product-image'>
			<img src="<?php echo Mage::helper('dealoffer/offers_image')->init($_offers, 'deal_image')->resize(200);?>" alt="<?php echo $this->htmlEscape($_offers->getName());?>"  style="vertical-align:middle;max-height:150px;" />
			</a>
			</div>
			<?php endif;?>
			<div class="bordder_bottom">&nbsp;</div>
			<div class="title"><?php echo $_offers->getName();?></div>
		</div>
	<?php 
	$j++;
	endforeach;?>
</div>
<script>
window.onload=function(){
	
	if(divlists.length > 0)
	{
		for(i=0;i<divlists.length;i++)
		{
			var arr = divlists[i].split("&&||&&"); 
			//alert(arr[1]);
			var dateFuture1 = new Date(arr[1]);
			GetCount_offer(dateFuture1, arr[0]);
		}
	
	}
	//you can add additional countdowns here (just make sure you create dateFuture2 and countbox2 etc for each)
}
</script>
<?php else : ?>
	<?php echo Mage::helper('dealoffer')->__('There are no offers at this moment');?>
<?php endif;?> 

