<?php 
/**
 * D4U_Dealoffer extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	D4U
 * @package		D4U_Dealoffer
 * @copyright  	Copyright (c) 2013
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Offers list template
 *
 * @category	D4U
 * @package		D4U_Dealoffer
 * @author Ultimate Module Creator
 */
 $division_cat =0;
?>
<script src="<?php echo $this->getJsUrl(); ?>d4u_dealoffer/countdown.js" type="text/javascript"></script>
<link rel='stylesheet' id='camera-css'  href="<?php echo $this->getSkinUrl('d4u_dealoffer/deal.css');?>" type='text/css' media='all'>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_offerss = $this->getOfferss(); ?>
<div class="page-title offers-title">
	<?php if(Mage::helper('dealoffer/offers')->isRssEnabled()) : ?>
		<a href="<?php echo Mage::helper('dealoffer/offers')->getRssUrl();?>" class="link-rss"><?php echo Mage::helper('dealoffer')->__('Subscribe to RSS Feed')?></a>
	<?php endif;?>
	<h1><?php echo Mage::helper('dealoffer')->__('Offers') ?></h1>
</div>
<?php
 if ($_offerss->getSize() > 0) :?>
<?php echo $this->getPagerHtml(); ?>
<div class="dela_offer"><br/><br/>
	<?php 
	$j=0;
	foreach ($_offerss as $_offers) : 
	$data = $_offers->getData();
	$current_cat = $data['category_id'];
	?>
		<div class="item">
		<?php 
		$category = Mage::getModel('catalog/category')->load($current_cat);
		?>
		
			<div style="height:45px;"><h3 class="top_category" style="float:left">&nbsp;&nbsp;<?php echo $category->getName();?></h3>	
			<div class="time" id="countboxoffer1_<?php echo $j?>" style="float:right"></div>
				<script>
					  divlists.push('countboxoffer1_<?php echo $j."&&||&&".date("Y/m/d", strtotime($data['end_date']));?>') ;
				</script>
		
			</div>
			
			<?php if ($_offers->getDealImage()) :?>
			<div class="item_center_image">
					<a href="<?php echo $_offers->getOffersUrl();?>" title="<?php echo $this->htmlEscape($_offers->getName()) ?>" class='product-image'>
					<img src="<?php echo Mage::helper('dealoffer/offers_image')->init($_offers, 'deal_image')->resize(250);?>" alt="<?php echo $this->htmlEscape($_offers->getName());?>" id="imgck" style="max-height:200px;" />
					</a>
			</div>
			<?php endif;?>
			<div class="bordder_bottom">&nbsp;</div>
			<div class="title"><?php echo $_offers->getName();?></div>
			<?php if($data['category_count'] > 1) {?>
			<div class="button"><a href="<?php echo $this->getUrl('dealoffer/offers/categoryview/',array('id'=>$current_cat)); ?>" class="btn-orange">View all offers</a></div>
			<?php } ?>
		</div>
	<?php 
	$j++;
	endforeach;?>
</div>
<script>
window.onload=function(){
	
	if(divlists.length > 0)
	{
		for(i=0;i<divlists.length;i++)
		{
			var arr = divlists[i].split("&&||&&"); 
			//alert(arr[1]);
			var dateFuture1 = new Date(arr[1]);
			GetCount_offer(dateFuture1, arr[0]);
		}
	
	}
	//you can add additional countdowns here (just make sure you create dateFuture2 and countbox2 etc for each)
}
</script>
<?php echo $this->getPagerHtml(); ?>
<?php else : ?>
	<?php echo Mage::helper('dealoffer')->__('There are no offers at this moment');?>
<?php endif;?> 

