<?php
$todayDate = Mage::app()->getLocale()->date()->toString(Varien_Date::DATE_INTERNAL_FORMAT);
$leftofferss   = Mage::getResourceModel('dealoffer/offers_collection')
 			->addStoreFilter(Mage::app()->getStore())
			->addFilter('status', 1)
			->customaddFilter('end_date', $todayDate ,">=")
			->customaddFilter('offer_image', 1 ,"=")
		  ;
	
		$leftofferss->GroupbyAdd('entity_id');
if($leftofferss->getSize() != 0) {
?>
<script src="<?php echo $this->getJsUrl(); ?>d4u_dealoffer/countdown.js" type="text/javascript"></script>
<style>
.time{
		background :none repeat scroll 0 0 #FAE683;
		border:1px solid #FAC903;
		color:#333333;
		font-size:15px;
		padding:0px 5px 0px 5px;
}
li.item { list-style: none outside none;}
.block-deal { 
	border :5px solid #000000;
	border-radius :8px;
	font-size:13px;
	line-height:1.25;

}
.block-deal-title {
background:#000;
color:#FFFFFF;
font-size:14px;
padding:5px;
text-align:center;
}
.deal-product-image{ border:1px solid #ccc;vertical-align:middle;max-height:160px;}
</style>
<?php 
foreach ($leftofferss as $leftoffers) {
	$leftdata = $leftoffers->getData();
	
?>
<div class="block block-deal">
    <div class="block-deal-title">
        <strong><?php echo $this->__("Today's Deal") ?></strong>
    </div>
    <div class="block-content">        
		
        <ol id="best-sidebar" class="mini-products-list">
        <li class="item">
			<div>
	            <p class="product-name">
	                <a href="<?php echo $leftoffers->getOffersUrl() ?>"><?php echo $leftoffers->getName();?></a>
	            </p>    
			</div>
			<div>
				<br/>
				<a href="<?php echo $leftoffers->getOffersUrl();?>" title="<?php echo $this->htmlEscape($leftoffers->getName()) ?>" ><img src="<?php echo Mage::helper('dealoffer/offers_image')->init($leftoffers, 'deal_image')->resize(166);?>" alt="<?php echo $this->htmlEscape($leftoffers->getName());?>" class='deal-product-image'/></a>
				<br/>
			</div>
            
        </li>
         <li class="item">
			
			<div >
					<div class="time" id="countboxofferleft" style="float:right"></div>
						<script>
							  leftdivlist.push('countboxofferleft<?php echo "&&||&&".date("Y/m/d", strtotime($leftdata['end_date']));?>') ;
						</script>
				</div>
		 </li>
        </ol>
        <div class="actions" style="margin-top:8px;">
        <button onclick="setLocation('<?php echo  $this->getUrl('dealoffer/offers');?>')" class="button" title="<?php echo $this->__('View All Offers') ?>" type="button"><span><span><?php echo $this->__('View All Offers') ?></span></span></button>
		</div>
		</div> 
<?php 

}

?>
<script>
window.onload=function(){
	
	if(leftdivlist.length > 0)
	{
		for(i=0;i<leftdivlist.length;i++)
		{
			var arr = leftdivlist[i].split("&&||&&"); 
			//alert(arr[1]);
			var dateFuture1 = new Date(arr[1]);
			GetCount_offer(dateFuture1, arr[0]);
		}
	
	}
	//you can add additional countdowns here (just make sure you create dateFuture2 and countbox2 etc for each)
}
</script>
</div>
<?php } ?>